name: Continuous integration (temp-biomodels)

on:
  # push:
  workflow_dispatch:

jobs:
  fixEntries:
    name: Fix the entries of BioModels and commit to the repository
    strategy:
      matrix:
<<<<<<< HEAD
          job: [0, 1, 2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
=======
        # job: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
        job: [0, 1, 2]
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
>>>>>>> ac0b02af0 (fix: fixed format of CI workflow)

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Setup pip cache
      uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/Python
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install pip and setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'

    - name: Install Systems Biology Format Converter (SBFC)
      run: |
        cd /tmp
        wget https://sourceforge.net/projects/sbfc/files/sbfc/sbfc-1.3.7.zip/download -O sbfc-1.3.7.zip
        unzip sbfc-1.3.7.zip
        mv sbfc-1.3.7 /opt/
        rm sbfc-1.3.7.zip
        echo "/opt/sbfc-1.3.7" >> $GITHUB_PATH

    - name: Install Octave
      run: |
        sudo apt update -y
        sudo apt-get install -y --no-install-recommends octave

    - name: Install Scilab
      run: sudo apt-get install -y --no-install-recommends scilab

    - name: Install XPP
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends wget make gcc libx11-dev libc6-dev

        cd /tmp
        wget http://www.math.pitt.edu/~bard/bardware/xppaut_latest.tar.gz
        mkdir xpp
        tar zxvf xppaut_latest.tar.gz --directory xpp
        cd xpp
        make
        sudo make install

        cd /tmp
        rm xppaut_latest.tar.gz
        rm -r xpp

    - name: Install BioModels QC
      working-directory: biomodels_qc
      run: |
        python -m pip install cython
        python -m pip install .

    - name: Install requirements
      run: python -m pip install -r requirements.txt

    - name: Fix entries
      run: python fix-entries.py --convert-files --validate-sbml --num-jobs 3 --job ${{ matrix.job }}

    - name: Setup Git
      run: |
        git config --global user.email "bot@reproduciblebiomodels.org"
        git config --global user.name "Center for Reproducible Biomodeling Modeling Bot"
        git config pull.rebase false

    - id: commit-final-entries
      name: Commit changes to the fixed entries
      run: |
        git stash
        git pull
        set +e
        git stash pop
        git add final/
        git commit -m "Automated update fixed versions of entries" -- final
        if [[ $? = 0 ]]; then
          finalEntriesChanged=1
        else
          finalEntriesChanged=0
        fi
        echo "::set-output name=finalEntriesChanged::$finalEntriesChanged"

    - name: Push the changes to the fixed entries
      if: steps.commit-final-entries.outputs.finalEntriesChanged == '1'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
